In [1]:
# Hello welcome to a new session

# in this we will work on basic pandas library

# install pandas
# !pip install pandas

# it is already install
import pandas as pd

In [3]:
dict = {
    "Name": ["Ashish", "Raj","Nikita","Pranjal"],
    "CGPA": [8.48, 8.8, 9.7, 7.6],
    "City": ["Gwalior", "Indore", "Delhi", "Wellington"]
}

In [4]:
# now we can load this dictionary data as a dataframe which is a 2d labelled dataset which is a collection of 1d 
# labelled dataset called series

# now to see and have data as dataframe we will use our pandas which we have imported as pd

df = pd.DataFrame(dict) # like this we can create dataframe, it is created in a varuable name df you can print it
print(df)
# after printing you can see how it has arranged it
# keys become columns, each value of columns makes row and the counting on left of it is labelling
# it starts from 0 same as indexing but we can change it

      Name  CGPA        City
0   Ashish  8.48     Gwalior
1      Raj  8.80      Indore
2   Nikita  9.70       Delhi
3  Pranjal  7.60  Wellington

In [6]:
df = pd.DataFrame(dict)
df

      Name  CGPA        City
0   Ashish  8.48     Gwalior
1      Raj  8.80      Indore
2   Nikita  9.70       Delhi
3  Pranjal  7.60  Wellington

In [11]:
# nowwe gonna work on the series in detail

# series is the 1D labelled data structure
# means it is not only indexed but labelled but they are king of same
# index here is positional argument only eg, s[0] will get you first element and so on
# label here is kind of name to it like by default it starts from 0, so s[0] will get you first element and so on 
# but you can change it while making the series and after it suppose you are storing the age and want to name of people as lebel

# normal series

s = pd.Series([23, 45, 22, 55, 33]) # normal way index = label here
print(s, type(s))
print()

# with changed index
s = pd.Series([26, 28, 27, 28, 26], index=["Nikita","Ashish","Raj","Pranjal","Devraj"]) # here we have labelled them with names
# but you can see and that is irony that the name labelled here is index😂😂

print(s, type(s))
print()

# we can print all labelles
print(s.index)

0    23
1    45
2    22
3    55
4    33
dtype: int64 <class 'pandas.Series'>

Nikita     26
Ashish     28
Raj        27
Pranjal    28
Devraj     26
dtype: int64 <class 'pandas.Series'>

Index(['Nikita', 'Ashish', 'Raj', 'Pranjal', 'Devraj'], dtype='str')

In [13]:
# now we see more about series
# pandas is based on numpy so thi series data structure is based on ndarray of numpy
# so it stores homogeneous data means data of same type, and if given non same data, it type cast it
s = pd.Series([1, 2, 3, 4, 5]) # here data is homogeneous
print(s, type(s))

# now lets cahnge it 
s = pd.Series([1, 2, 3, "Hello", 4.6])
print(s, type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
0        1
1        2
2        3
3    Hello
4      4.6
dtype: object <class 'pandas.Series'>

In [20]:
# ypu can do operations here by vectorization like
s = pd.Series([1, 2, 3, 4, 5])
print(s * 5)
print(s / 2)

# now you can not change the size of Series (it is immutable) but you can change the values of series (they are mutable)
s[0] = 100
print(s)

# now value at index 0 become 100
# but if you drop the value this will not work
s.drop(0) # looks that it worked but no lets print s again
print()
print(s) # you will found 100 again, hence dropping something will result into reduction of size and this is not possible so 
# we store series with dropped element in a new variable and make new series

new_s = s.drop(0)
print(s)
print(new_s)

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
s_sum = s1 + s2
print(s_sum) # these are series for now wedo that for series, if i have more i will share

0     5
1    10
2    15
3    20
4    25
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64
0    100
1      2
2      3
3      4
4      5
dtype: int64

0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64
0     7
1     9
2    11
3    13
4    15
dtype: int64

In [25]:
# Now we see dataframes in detail
# they are 2D ndarray so lets make them with dictionary once again
dict = {
    "Name": ["Ashish", "Raj", "Pranjal"],
    "Age": [28, 27, 28],
    "cgpa": [8.4, 8.8, 8.3]
}

df = pd.DataFrame(dict) # creating it with dictionary and here key become column names and values of them become columns
# and each value from column combinely becomes row

print(df, type(df))
print(df.index) # indexes for row
print(df.columns) # printing the column names

      Name  Age  cgpa
0   Ashish   28   8.4
1      Raj   27   8.8
2  Pranjal   28   8.3 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'cgpa'], dtype='str')

In [30]:
# now lets make it with list becuase it is 2D so we create a 2D list
list1 = [["Ashish", 28, 8.4],["Raj", 27, 8.8],["Pranjal", 28, 8.3]]
# you can see how this is each individual list is a complete row and these values separately gives us column number
list2 = [["Ashish", "Raj", "Pranjal"],[28, 27, 28],[8.4, 8.8, 8.3]]
df = pd.DataFrame(list2, index=["Name", "Age", "cgpa"]) # here we are giving indexes and in next one we are giving the 
# columns
print(df, type(df))
# when we create dataframe out of this we need to give column heads or names because weithout it would not look nice
df = pd.DataFrame(list1, columns=["Name", "Age", "cgpa"])
print(df, type(df))

# so in this example you can see you can do it both ways

           0    1        2
Name  Ashish  Raj  Pranjal
Age       28   27       28
cgpa     8.4  8.8      8.3 <class 'pandas.DataFrame'>
      Name  Age  cgpa
0   Ashish   28   8.4
1      Raj   27   8.8
2  Pranjal   28   8.3 <class 'pandas.DataFrame'>

In [32]:
df # see tabular form of it

      Name  Age  cgpa
0   Ashish   28   8.4
1      Raj   27   8.8
2  Pranjal   28   8.3

In [34]:
# now we will create it with numpy array
import numpy as np
np_arr = np.array([["Ashish", 28, 8.4],["Raj", 27, 8.8],["Pranjla", 28, 8.3]]) # here we know axis 0 gives row for 2D and axis 1 gives column so according to data we follow the each individual list as complete row
print(np_arr)

# now we create dataframe
df = pd.DataFrame(np_arr, columns =["Name", "Age", "CGPA"])
print(df, type(df))

[['Ashish' '28' '8.4']
 ['Raj' '27' '8.8']
 ['Pranjla' '28' '8.3']]
      Name Age CGPA
0   Ashish  28  8.4
1      Raj  27  8.8
2  Pranjla  28  8.3 <class 'pandas.DataFrame'>

In [35]:
df

      Name Age CGPA
0   Ashish  28  8.4
1      Raj  27  8.8
2  Pranjla  28  8.3

In [3]:
# so these things we can do but most of the time we have to import the data through external files
# so now we open a csv file in pandas
df_csv = pd.read_csv("employee_data.csv")
print(type(df_csv))
df_csv # so it is that easy

<class 'pandas.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [5]:
# this time we use json file
df_json = pd.read_json("employee_data.json")
print(type(df_json))
df_json

# there are method like read_excel and read_sql, which we will use later

<class 'pandas.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [6]:
# now we will see our data of csv in detail so first  thing we print it
df_csv

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [7]:
# now if you want to print the first 5 rows
df_csv.head() # by default it gives 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [8]:
# to get any number of first rows 
df_csv.head(3)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000

In [9]:
# same for tail also
df_csv.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [10]:
df_csv.tail(7)

   ID    Name  Age Department  Salary
3   4   David   45  Marketing   91000
4   5     Eva   38         IT   65000
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [11]:
# now we have sample, if you want any random row
df_csv.sample()

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000

In [12]:
# for multiple sample rows give it a number
df_csv.sample(6)

   ID     Name  Age Department  Salary
2   3  Charlie   28    Finance   48000
1   2      Bob   32         IT   72000
3   4    David   45  Marketing   91000
6   7    Grace   41         HR   82000
4   5      Eva   38         IT   65000
0   1    Alice   25         HR   55000

In [13]:
# suppose you want to know basic info of data like how many rows and columns and type of data
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

In [15]:
# if you want to see the shape of it
shape = df_csv.shape # well this is tuple and a value so do not use parenthesis after it as it is not function
print(shape)
print(df_csv.shape) # you can print directly

(10, 5)
(10, 5)

In [17]:
# then we have describe which gives basic calculations on mathematical data inside dataframe
df_csv.describe() # you can see maximum, minimum, mean, count, standard deviation, percentile on each column where maths is possible

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [19]:
# to get to use how many unique values are there in columns we can use
df_csv.nunique() # this will give you about how many unique values a column has

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64